### ISSUE TITLE
Presets for "When"

### ISSUE THREAD

**Issue by georgjaehnig** [derhuerst/vbb-telegram#1]
Hi,

thanks for your bot, I like it! (And I think, we've met last year at the Coding Amigos ;))

To save the user some typing, can you add some preset "options" when asking for when? For example, I don't want to literally type "now", I'd like to have it offered and just tap it.

Or: Can you allow some shortcuts? Like
- `n` for "now"
- `10m` for "in 10 minutes"
- `5h` for "in 5 hours"

Thanks! :)

**Comment by derhuerst** [comment]
@georgjaehnig 

> thanks for your bot, I like it!

That's nice to hear!

> And I think, we've met last year at the Coding Amigos ;)

We did.

> To save the user some typing, can you add some preset "options" when asking for when? For example, I don't want to literally type "now", I'd like to have it offered and just tap it.

Nice idea. Will do that.

> Or: Can you allow some shortcuts? Like

In fact, not only these forms are possible, put everything that [parse-messy-time](https://github.com/substack/parse-messy-time#parse-messy-time) can parse.

> - 10m for "in 10 minutes"

["in 10m" works](https://tonicdev.com/56c5d4d31608df0c0039061c/5787fe48b1b2651400778be4)

**Comment by derhuerst** [comment]
Done as of 5c486c9.
